### PR TITLE
Add constructor functions for missing text attributes

### PR DESCRIPTION
**Pull request by darioteixeira**
I tried to keep the same conventions already used in Tyxml.  I just wasn't sure about `linethrough`: should it be `lineThrough` or `line_through` instead?

### CODE REVIEW

**Comment by Drup** [comment]
I vote for `line_through`. Please put a link to the standard in the commit message, it helps. :)

**Comment by Drup** [comment]
Actually, hold that fix. Let's discuss a consistent naming scheme first.

**Comment by darioteixeira** [comment]
Note: I named the PVs `Text_Anchor`, `Text_Decoration`, and `Text_Rendering` because those were the names already declared in `svg_types.mli`.  Otherwise, I tried to stick to the newly published Tyxml's casing conventions.

**Comment by pveber** [comment]
This PR would be useful to me too. If I can be of any help to finalize it, I'd happily give a hand.

**Comment by Drup** [comment]
Woops, I forgot about it after publishing the casing conventions!

Some help to actually apply these conventions to already defined elements would be really welcome though. ;)

**Pull request merged**
