### PR TITLE
Fix link without versions numbers with symlink

### PR DESCRIPTION
**Pull request by CelieArnaud**

### CODE REVIEW

**Comment by vasilisp** [comment]
@Drup the same fix works for Ocsigen Start (https://github.com/ocsigen/ocsigen-start/pull/502) so I take the liberty of merging a TyXML PR :).

**Comment by Drup** [comment]
@CelieArnaud @vasilisp It would be nice to have some sort of documentation on how I'm supposed to make new dev documentation now.

**Comment by Drup** [comment]
(Still, thanks!)

**Comment by CelieArnaud** [comment]
Yes, I'm working on it.
(You're welcome)

**Pull request merged**
