### PR TITLE
More SVG fixes

### PR DESCRIPTION
**Pull request by aantron**

### CODE REVIEW

**Comment by Drup** [comment]
Wow, thanks! :tada:

**Comment by Drup** [comment]
One of the test seems to fail.

**Comment by aantron** [comment]
Not with current Markup.ml. Already pinning it in Jenkins now.

**Comment by aantron** [comment]
I'll just make a new PR for the Jenkins pin, then I will rebase both PRs over it after merging that. BTW, TyXML has required a newer Markup.ml than in OPAM this whole time, we just weren't testing enough to see it... :)

**Pull request merged**
