### PR TITLE
Various simplification in trivial attributes.

### PR DESCRIPTION
**Pull request by Drup**
I think I'm going to wait before merging this one for the next major version of tyxml (along with some other breaking changes) in order not to break compat in each minor version of tyxml...

### CODE REVIEW

**Comment by vasilisp** [comment]
JSOO looks unaffected. Eliom update in the works.

**Comment by Drup** [comment]
@vasilisp I think it's best to wait for all the changes in tyxml to be done (that's only the start). Just use stable tyxml for now ...

**Comment by vasilisp** [comment]
I had updated everything before reading your message (and we had broken compatibility with stable before). Also, if the other packages don't work with TyXML master, how are we going to find any issues?

**Comment by Drup** [comment]
@vasilisp By testing before tyxml release ? :)
It's not going to be right now anyway.

**Pull request merged**
