### PR TITLE
Add support for the `role` attribute.

### LINKED ISSUE #165: Missing `a_role`
`a_role` seemed to be missing for the `a` element.

### PR DESCRIPTION
**Pull request by Armael**
See https://www.w3.org/TR/role-attribute/ and also https://www.w3.org/TR/wai-aria/

Fixes #165

### CODE REVIEW

**Comment by Armael** [comment]
I'm not 100% sure if `role` can actually be put on any element, given my inability to decipher the w3c doc page linked in the previous message.

**Comment by Drup** [comment]
The documentation seems ill-formated. From the log, it seems ocamldoc doesn't like your @see tag.

**Comment by Armael** [comment]
Indeed. I fixed the documentation and added a few more links.

**Comment by Drup** [comment]
The w3c documentation is never a masterpiece of clarity, but in this case, I also think it should be available on all elements. Thanks!

**Pull request merged**
